prefixsum-seq: prefixsum-seq.c secret.c 
	gcc -std=c99 -O2 prefixsum-seq.c secret.c -o prefixsum-seq

prefixsum-mul: prefixsum-mul.c secret.c
	gcc -std=c99 -O2 prefixsum-mul.c secret.c -o prefixsum-mul -lpthread 
